### ISSUE TITLE
Local host

### ISSUE THREAD

**Issue by albercher** [learn-co-curriculum/react-hooks-npm-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/4550/assignments/157562?module_item_id=335736

### Concern

I installed the packages correctly but was unable to get the clock to work. when I ran "npm start" I got this error:
npm ERR! Missing script: "start"

When I finally got it to work, it used localhost:3000, not localhost5000 as said in the readme.

**Comment by ihollander** [comment]
Hi @albercher - thanks for flagging this issue! It looks like the `serve` npm package recently changed the default port from 5000 to 3000:

https://github.com/vercel/serve/pull/680

I'll update the lesson to reflect this change.
