### ISSUE TITLE
My JSON server uses http://localhost:3000/

### ISSUE THREAD

**Issue by OneShepForward** [learn-co-curriculum/react-hooks-npm-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/4550/assignments/157562?confetti=true&submitted=0

### Concern

The instructions say "Run npm start to run this script, and open up localhost:5000 (Links to an external site.) in the browser.", but my JSON server uses 3000 by default. 

Maybe realizing it could be different is part of the challenge though? I passed!

**Comment by ihollander** [comment]
Hi @OneShepForward - thanks for flagging this issue! It looks like the serve npm package recently changed the default port from 5000 to 3000:

http://github.com/vercel/serve#680

The lesson has been updated: #5
